Exercise 3
cc1000/DevOps-Course-Starter pull request #3
Opened 2020-08-01 17:22 UTC by cc1000

2020-08-18 13:45 UTC, hugh-emerson requested changes
The tests look good. Just see my comments on the e2e test file for a change to get it working without relying on any extra env var set up. 

Also, you seem to have an unexpected byte at the start of requirements.txt which makes git think it's a binary file. Try recreating it from pip freeze to fix it.

2020-08-18 13:45 UTC, hugh-emerson commented on README.md
> +Download the Gecko Driver exe from [here](https://github.com/mozilla/geckodriver/releases/latest) and extract exe to root project directory.
Good job updating the README, but it would be good to also add instructions for how to actually run the tests.

To make things slightly easier for the dev, you could update .env.template to include blank or default values for your 4 new environment variables. The setup script copies .env.template into .env the first time it's run.

2020-08-18 13:45 UTC, hugh-emerson commented on .gitignore
> +geckodriver.exe
geckodriver.log should also be ignored. It's already being tracked so you'll need to make sure it's deleted from the repo first.

2020-08-18 13:45 UTC, hugh-emerson commented on tests_e2e/test_e2e_tests.py
> +    board_name = f'Corndell_tests_{uuid.uuid4()}'
Unless you are running with e.g. VSCode settings to automatically load the .env file, you'll need to add `load_dotenv(find_dotenv('.env'), override=True)` here for the tests to pass. Then you should be able to run `pytest tests_e2e` from command line as well.

2020-08-25 07:01 UTC, cc1000 commented
Updated as per comments above. See https://github.com/cc1000/DevOps-Course-Starter/pull/3/commits/47a8fb2cf38a06c70c9bed5497caf765858ce49a.

2020-08-25 13:41 UTC, hugh-emerson approved these changes
Looks good. I've left a small comment on the README but go ahead and merge when you're ready 👍

2020-08-25 13:41 UTC, hugh-emerson commented on README.md
> +
You also need to have Firefox installed

2020-08-25 19:28 UTC, merged